[package]
name = "rails_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
glob = "0.3.1"
log = "0.4.17"
log4rs = "1.2.0"
ratatui = "0.20.1"
